version: '3.8'

services:
  # Frontend Widget
  widget:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: twenty-phone-widget
    ports:
      - "3003:80"
    env_file:
      - .env.production
    restart: always
    networks:
      - widget-network
    depends_on:
      - token-server
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Token Server
  token-server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: twenty-token-server
    ports:
      - "3001:3001"
    env_file:
      - .env.production
    restart: always
    networks:
      - widget-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  widget-network:
    driver: bridge

volumes:
  widget-data:
    driver: local